spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coupang?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    defer-datasource-initialization: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: none

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: qweqweqqweqweqweqweqeqweqweqwewqeqeqweqweqwe123

